### ISSUE TITLE
Supplemental Tree Maintenance Detail - Add Plant Size Field

### ISSUE THREAD

**Issue by JingwenX** [york-region-tpss/stp#115]

**Comment by JingwenX** [comment]
Would you provide a list of plant types?

**Comment by lyb2010** [comment]
@JingwenX , list of plant types provided by business:

 1             Coniferous - 100 cm
2              Coniferous - 150 cm
3              Coniferous - 200 cm
4              Deciduous - 50 mm
5              Deciduous - 150 cm
6              Shrub - 50 cm
7              Transplant Tree 50 m
8              Transplant Tree 500 m
9              Transplant Tree 2000 m

**Comment by JingwenX** [comment]
@garykang1476  How to add an extra field to the form?
