### ISSUE TITLE
Summary of Contract Items

### ISSUE THREAD

**Issue by garykang1476** [york-region-tpss/stp#15]
Build up report for four summary of contract items.

- no break down
- break down by area forester
- break down by municipality
- break down by program

**Comment by garykang1476** [comment]
@lyb2010 sample for the reports are needed

**Comment by lyb2010** [comment]
Please see sample report attached.
[report Summary of Contract Items By Municipality.docx](https://github.com/york-region-tpss/stp/files/1376602/report.Summary.of.Contract.Items.By.Municipality.docx)
