### ISSUE TITLE
Bid form summary

### ISSUE THREAD

**Issue by garykang1476** [york-region-tpss/stp#17]
sample needed

**Comment by lyb2010** [comment]
Please find the attached sample report for Bid Form Summary.
[report Bid Form Summary.docx](https://github.com/york-region-tpss/stp/files/1376663/report.Bid.Form.Summary.docx)

**Comment by garykang1476** [comment]
Satisfied! Thank you @lyb2010

**Comment by garykang1476** [comment]
Job is done, please review @hunterls97

**Comment by hunterls97** [comment]
reviewed, everything is good
