### ISSUE TITLE
Tree Planting Payment Replica

### ISSUE THREAD

**Issue by garykang1476** [york-region-tpss/stp#4]
Replicate the functionality from old system. 

#### Payment Status ####
- Assigned For Payment
- Not Ready 
- Paied - Commited

![image](https://cloud.githubusercontent.com/assets/3499016/26500372/aab91aa8-4203-11e7-8937-960f14d3b74f.png)

![image](https://cloud.githubusercontent.com/assets/3499016/26500434/ed7a8a8e-4203-11e7-91a8-407524effd00.png)

#### Report Print out ####
- Based on auto-assigned payment number
- Current means Assigned For Payment items

**Comment by garykang1476** [comment]
The functionality in current system is super slow

**Comment by lyb2010** [comment]
[SAMPLE Payment Certificate Tree Plant Inspection.pdf](https://github.com/york-region-tpss/stp/files/1048599/SAMPLE.Payment.Certificate.Tree.Plant.Inspection.pdf)

**Comment by garykang1476** [comment]
For the Payment Status, there are four different states.
- Not Ready
- Ready for Payment
- Assigned For Payment
- Paid

There are two actions related to the Payment Status:
- Checkbox & Save
This will alter the status from **Ready for Payment** and **Assigned For Payment**. Other statuses will hide the checkbox.
- Commit to Payment
This will assign a payment certificate number to the rows that have status **Assigned For Payment**

**Comment by hunterls97** [comment]
questions:
is it possible for 1 tree ID to have multiple activity types? 
For Ready status (tree has deficiency) do we assume the most recent record to be correct?
|__> select *  from STP_DEFICIENCY_V  where TREEID = 2005005 order by CREATEDATE desc

**Comment by garykang1476** [comment]
> questions:
> is it possible for 1 tree ID to have multiple activity types?
> For Ready status (tree has deficiency) do we assume the most recent record to be correct?
> |__> select * from STP_DEFICIENCY_V where TREEID = 2005005 order by CREATEDATE desc

Yes, we should use treeid plus activity_type as the primary key

**Comment by hunterls97** [comment]
questions: 
- some TREEID's have 2 contract items example: treeid 6007389 is in contract item 1 and 72
- Old system seems to have fields displaying not ready where the database shows most recent data should display as ready.

**Comment by lyb2010** [comment]
Business user if not ready to proceed with task, on hold until further notice

**Comment by hunterls97** [comment]
question:
When assigning a tree for payment that has both tree planting and stumping activity types, should both be selected if either one is?

**Comment by garykang1476** [comment]
> When assigning a tree for payment that has both tree planting and stumping activity types, should both be selected if either one is?

yes, they are separate items. @hunterls97
