### ISSUE TITLE
Deficiency Report

### ISSUE THREAD

**Issue by garykang1476** [york-region-tpss/stp#5]
Create in application dashboard for deficiency reports, 

## Enhancement ##
Add a date range filter

## Question ##
Print out functionality does not work in the demo system of stp, Template and Knowledge transfer need to be provided
**Answer**: See Ly's comment below.

**Comment by lyb2010** [comment]
[SAMPLE Tree Planting Deficiency Report.xlsx](https://github.com/york-region-tpss/stp/files/1039357/SAMPLE.Tree.Planting.Deficiency.Report.xlsx)

Is this sufficient?

**Comment by garykang1476** [comment]
> SAMPLE Tree Planting Deficiency Report.xlsx
> 
> Is this sufficient?

Yes, thanks, I would remove the question tag.

**Comment by garykang1476** [comment]
@lyb2010 Please follow up with Adam to get the file samples downloaded from production, I have talked to him earlier today

**Comment by lyb2010** [comment]
[Copy of Tree Planting Deficiency List 2017_excel.xlsx](https://github.com/york-region-tpss/stp/files/1061964/Copy.of.Tree.Planting.Deficiency.List.2017_excel.xlsx)
[Deficiency List summary.pdf](https://github.com/york-region-tpss/stp/files/1061965/Deficiency.List.summary.pdf)
[Def List _ PDF.pdf](https://github.com/york-region-tpss/stp/files/1061966/Def.List._.PDF.pdf)

@garykang1476  Sample files from Adam

**Comment by hunterls97** [comment]
@lyb2010 Can you ask Adam for a list with the descriptions of each deficiency, and a description of the required repairs for that deficiency?
