### ISSUE TITLE
Contractor Repairs Tree Planting Deficiencies

### ISSUE THREAD

**Issue by garykang1476** [york-region-tpss/stp#6]
Replica from old system.

**Comment by lyb2010** [comment]
[SAMPLE Contractor Repair Tree Planting Deficiency Report.xlsx](https://github.com/york-region-tpss/stp/files/1052756/SAMPLE.Contractor.Repair.Tree.Planting.Deficiency.Report.xlsx)

**Comment by hunterls97** [comment]
Question:
Old system has one location per contract item, but some contract items have many corresponding locations depending on the tree within the RIN. How does the old system decide which location to use in these cases?
